### ISSUE TITLE
Delay when clicking Proceed....

### ISSUE THREAD

**Issue by MartinBondCanada** [adixon/ca.civicrm.iats#17]
We  have  noticed  lately that our client's client are having  delays when they click to process a transaction using iATS and CiviCRM.  Because  of  those  delays, many clicked again on the action button  and  we have 6 transaction that were diplicated (2 to 4 times) and had to do a few refunds.

My  question  is: where does that delay come from ? Can it be iATS server being slow to respond or our CiviCRM installation ?

All hints are welcome ;-)

Thanks,

Martin

**Comment by KarinG** [comment]
Hi Martin - first thing to do would be to ensure you're on the latest version of the iATS Extension. It moved project homes at some point last year: you can find it here: https://github.com/iATSPayments/com.iatspayments.civicrm - if you then still see this issue - report it to us there - and then we can try dig into it. -- KarinG

**Comment by adixon** [comment]
I have had this occur in a few isolated cases, and I think it might be a combination of the two, but it's hard to say without more details. If you're getting it consistently, then I'd guess it to be your server, or the network connection from your server over to the iATS one. The extra server overhead when making that connection is related to the soap extension, so that'd be one place to pay attention. The network issue can usually be diagnosed with a traceroute command.
